# Excute the service's Makefile

# Bug if not extecuted from optics package dir (ie in emacs started elsewhere)
MEMEROOT=$(realpath ../../../../../../../../..)

.PHONY : default 

default : 
	$(MAKE) -C ../../../../../../.. $(MAKEFLAGS)

