variables:
    GIT_SSL_NO_VERIFY: "true"
    MAVEN_CLI_OPTS: "--batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

test:
    script:
        - yum install ant junit ant-junit maven -y
        - ant test
    only:
        - master
        - /^site.sns.*$/

.maven: &maven
    image: europeanspallationsource/oracle-jdk-maven-jenkins:8
    only:
        - /^site.ess.*$/
build.maven:
    <<: *maven
    stage: build
    script:
        - 'mvn -DskipTests -Dmaven.javadoc.skip=true install'
.maventest: &maventest
    <<: *maven
    stage: test
    script:
        - 'cd $SUBDIR'
        - 'mvn verify -Dmaven.javadoc.skip=true -fn | tee std.out'
        - '! grep "Build failures were ignored" std.out'
    artifacts:
        reports:
            junit:
                - "$SUBDIR/target/surefire-reports/TEST-*.xml"
                - "$SUBDIR/*/target/surefire-reports/TEST-*.xml"
test.maven.apps:
    <<: *maventest
    variables:
        SUBDIR: 'apps'
test.maven.core:
    <<: *maventest
    variables:
        SUBDIR: 'test'
test.maven.extensions:
    <<: *maventest
    variables:
        SUBDIR: 'extensions'
test.maven.plugins:
    <<: *maventest
    variables:
        SUBDIR: 'plugins'
sonarqube.maven:
    <<: *maven
    stage: deploy
    script:
        - 'mvn -Dsonar.login={{SONAR_TOKEN}} sonar:sonar'
    only:
        - /^site.ess.*$/
publish.maven:
    <<: *maven
    stage: deploy
    script:
        - 'mvn deploy -pl dist -Dartifactory.username={{ARTIFACTORY_USERNAME}} -Dartifactory.password={{ARTIFACTORY_PASSWORD}}'
    only:
        - site.ess.master@ess-crs/openxal
pages:
    <<: *maven
    script:
        - 'mvn javadoc:aggregate'
        - 'mvn jacoco:report-aggregate'
        - 'mv report/target/site/jacoco-aggregate target/site/apidocs/coverage'
        - 'mv target/site/apidocs public'
    artifacts:
        paths:
            - public
    only:
        - site.ess.master
