variables:
    GIT_SSL_NO_VERIFY: "true"
test:
    script:
        - yum install ant junit ant-junit maven -y
        - ant test
    only:
        - master
        - /^site.sns.*$/

.maven: &maven
    image: registry.esss.lu.se/yngvelevinsen/dockers/oracle-jdk-maven:1.8
    only:
        - /^site.ess.*$/
build.maven:
    <<: *maven
    stage: build
    script:
        - 'mvn -DskipTests -Dmaven.javadoc.skip=true install -B'
.maventest: &maventest
    <<: *maven
    stage: test
    script:
        - 'mvn -DskipTests -Dmaven.javadoc.skip=true install -B'
        - 'cd $SUBDIR'
        - 'mvn verify -Dmaven.javadoc.skip=true -fn -B | tee std.out'
        - '! grep "Build failures were ignored" std.out'
    artifacts:
        reports:
            junit:
                - "$SUBDIR/target/surefire-reports/TEST-*.xml"
                - "$SUBDIR/*/target/surefire-reports/TEST-*.xml"
test.maven.apps:
    <<: *maventest
    variables:
        SUBDIR: 'apps'
test.maven.core:
    <<: *maventest
    variables:
        SUBDIR: 'test'
test.maven.extensions:
    <<: *maventest
    variables:
        SUBDIR: 'extensions'
test.maven.plugins:
    <<: *maventest
    variables:
        SUBDIR: 'plugins'
sonarqube.maven:
    <<: *maven
    stage: deploy
    script:
        - 'mvn -Dsonar.login={{SONAR_TOKEN}} sonar:sonar'
    only:
        - /^site.ess.never*$/
publish.maven:
    <<: *maven
    stage: deploy
    script:
        - 'mvn deploy -pl dist -Dartifactory.username={{ARTIFACTORY_USERNAME}} -Dartifactory.password={{ARTIFACTORY_PASSWORD}}'
    only:
        - site.ess.master.never@ess-crs/openxal
pages:
    <<: *maven
    script:
        - 'mvn -Dmaven.javadoc.skip=true install -B'
        - 'mvn javadoc:aggregate -B'
        - 'mvn jacoco:report-aggregate -B'
        - 'mv report/target/site/jacoco-aggregate target/site/apidocs/coverage'
        - 'mv target/site/apidocs public'
    artifacts:
        paths:
            - public
    only:
        - site.ess.master
        - site.ess.devel.gitlab-junit

