variables:
    GIT_SSL_NO_VERIFY: "true"
test:
    script:
        - yum install ant junit ant-junit maven -y
        - ant test
    only:
        - master
        - /^site.sns.*$/
test.maven:
    image: registry.esss.lu.se/yngvelevinsen/dockers/oracle-jdk-maven:1.8
    script:
        - mvn package -B
    artifacts:
        reports:
            junit: "**/target/surefire-reports/TEST-*.xml"
    only:
        - /^site.ess.*$/

