
ALTER TABLE "MACHINE_MODEL"."RUNS"
  DROP CONSTRAINT ckc_run_source_chk_runs;

ALTER TABLE "MACHINE_MODEL"."RUNS"
  ADD CONSTRAINT ckc_run_source_chk_runs CHECK  ( "RUN_SOURCE_CHK" IS NULL OR ( "RUN_SOURCE_CHK" IN ('DESIGN','EXTANT','PVLOGGER','MANUAL') ))
  
