ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "ALPHA_Z"                  NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "BETA_Z"                   NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "PSI_Z"                    NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "ETA_Z"                    NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "ETAP_Z"                   NUMERIC;     
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "R17"                      NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "R27"                      NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "R37"                      NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "R47"                      NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "R57"                      NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "R67"                      NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "R71"                      NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "R72"                      NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "R73"                      NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "R74"                      NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "R75"                      NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "R76"                      NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "R77"                      NUMERIC;
ALTER TABLE "MACHINE_MODEL"."ELEMENT_MODELS" ADD COLUMN    "DEVICE_TYPE"              VARCHAR(30);

 -- displays all GOLD models, the last DESIGN and EXTAND marked with 'PRESENT'
CREATE OR REPLACE VIEW "MACHINE_MODEL"."V_GOLD_REPORT" AS
(SELECT G."ID", G."RUNS_ID" as "RUN_ID", 'PRESENT' as "GOLD_STATUS_NO_CSS", G."COMMENTS", G."CREATED_BY", G."DATE_CREATED", R."RUN_SOURCE_CHK"  FROM "MACHINE_MODEL"."GOLD" G, "MACHINE_MODEL"."RUNS" R
WHERE 
  G."RUNS_ID" = R."ID" and
  R."RUN_SOURCE_CHK" = 'DESIGN'
ORDER BY 
  G."DATE_CREATED" DESC
LIMIT 1)

UNION

(SELECT G."ID", G."RUNS_ID" as "RUN_ID", 'PRESENT' as "GOLD_STATUS_NO_CSS", G."COMMENTS", G."CREATED_BY", G."DATE_CREATED", R."RUN_SOURCE_CHK"  FROM "MACHINE_MODEL"."GOLD" G, "MACHINE_MODEL"."RUNS" R
WHERE 
  G."RUNS_ID" = R."ID" and
  R."RUN_SOURCE_CHK" = 'EXTANT'
ORDER BY 
  G."DATE_CREATED" DESC
LIMIT 1)

UNION

(SELECT G."ID", G."RUNS_ID" as "RUN_ID", 'PRESENT' as "GOLD_STATUS_NO_CSS", G."COMMENTS", G."CREATED_BY", G."DATE_CREATED", R."RUN_SOURCE_CHK"  FROM "MACHINE_MODEL"."GOLD" G, "MACHINE_MODEL"."RUNS" R
WHERE 
  G."RUNS_ID" = R."ID" and
  R."RUN_SOURCE_CHK" = 'MANUAL'
ORDER BY 
  G."DATE_CREATED" DESC
LIMIT 1)
 
UNION

(SELECT G."ID", G."RUNS_ID" as "RUN_ID", 'PREVIOUS' as "GOLD_STATUS_NO_CSS", G."COMMENTS", G."CREATED_BY", G."DATE_CREATED", R."RUN_SOURCE_CHK"  FROM "MACHINE_MODEL"."GOLD" G, "MACHINE_MODEL"."RUNS" R
WHERE 
  G."RUNS_ID" = R."ID"
ORDER BY 
  G."DATE_CREATED" DESC
);
