ALTER TABLE "MACHINE_MODEL"."MODEL_DEVICES" ADD COLUMN "ELEMENT_NAME" VARCHAR(60);
ALTER TABLE "MACHINE_MODEL"."MODEL_DEVICES" ADD COLUMN "ZPOS" NUMERIC;
ALTER TABLE "MACHINE_MODEL"."MODEL_DEVICES"
  DROP CONSTRAINT "MODEL_DEVICES_DEVICE_TYPES_ID_fkey";