/*
 * EnvTrackerAdapt.java
 *
 *  Created on November 21, 2003, 11:14 AM
 *  Modified:
 *      12/02   - CKA
 *      9/03    - CKA: added space charge interval prediction
 *                   : added rotation into ellipsoid coordinates
 *      11/03   - CKA: full-second order adaptive step size
 *      11/03   - CKA: choice of integration accuracy order
 */
package xal.model.alg;

import java.util.logging.Level;
import java.util.logging.Logger;
import xal.model.IElement;
import xal.model.IProbe;
import xal.model.ModelException;
import xal.model.elem.IdealDrift;
import xal.model.elem.IdealRfGap;
import xal.model.elem.ThinElement;
import xal.model.probe.EnvelopeProbe;
import xal.model.probe.traj.EnvelopeProbeState;
import xal.tools.beam.CovarianceMatrix;
import xal.tools.beam.PhaseMap;
import xal.tools.beam.PhaseMatrix;
import xal.tools.beam.Twiss;
import xal.tools.data.DataAdaptor;
import xal.tools.data.DataFormatException;
import xal.tools.data.DataTable;
import xal.tools.data.EditContext;
import xal.tools.data.GenericRecord;

/**
 * <p>
 * Tracking algorithm for <code>EnvelopeProbe</code>'s. The
 * <code>EnvelopeProbe</code>'s state, which is a <code>CovarianceMatrix</code>
 * object, is advanced using the linear dynamics portion of any beamline element
 * (<code>IElement</code> exposing object) transfer map. The linear portion is
 * represented as a matrix, thus, the state advance is accomplished with a
 * transpose conjugation with this matrix.
 * </p>
 * <p>
 * The effects of space charge are also included in the dynamics calculations.
 * Space charge effects are also represented with a matrix transpose
 * conjugation, however, the matrix is computed using the values of the probe's
 * correlation matrix. The result is a nonlinear effect. The space charge forces
 * are computed using a linear fit to the fields generated by an ellipsoidal
 * charge distribution with the same statistics described in the probe's
 * correlation matrix. The linear fit is weighted by the beam distribution
 * itself, so it is more accurate in regions of higher charged density. For a
 * complete description see the reference below.
 * </p>
 * <p>
 * This algorithm uses a second-order accurate, adaptive step sizing algorithm
 * where the step size is continually adjusted to maintain an given error
 * tolerance in the residual.
 * </p>
 *
 * @see xal.tools.beam.em.BeamEllipsoid
 * @see <a href="http://lib-www.lanl.gov/cgi-bin/getfile?00796950.pdf">Theory
 * and Technique of Beam Envelope Simulation</a>
 *
 * @author Christopher K. Allen
 */
public class EnvTrackerAdapt extends EnvelopeTrackerBase {

    private static final Logger LOGGER = Logger.getLogger(EnvTrackerAdapt.class.getName());

    // Archiving constants 
    /**
     * EditContext label for table containing adaptive tracker parameters
     */
    private static final String TBL_LBL_ENVTRACKERADAPT = "EnvTrackerAdapt";

    /**
     * attribute label for maximum step size
     */
    private static final String ATTRTAG_MAXSTEP = "maxstep";

    /**
     * attribute label for maximum step size for drift space with pmq , sako 21
     * jul 06
     */
    private static final String ATTRTAG_MAXSTEP_DRIFTPMQ = "maxstepdriftpmq";

    /**
     * attribute label for initial step size
     */
    private static final String ATTRTAG_INITSTEP = "initstep";

    /**
     * attribute label for error tolerance
     */
    private static final String ATTRTAG_ERRTOL = "errortol";

    /**
     * attribute label for slack tolerance
     */
    private static final String ATTRTAG_SLACK = "slack";

    /**
     * attribute label for residual norm
     */
    private static final String ATTRTAG_NORM = "norm";

    /**
     * attribute label for maximum iteration count
     */
    private static final String ATTRTAG_MAXITER = "maxiter";

    /**
     * data node label for EnvTrackerAdapt settings
     */
    private static final String NODETAG_ADAPT = "adapt";

    /**
     * attribute label for order of accuracy in algorithm
     */
    private static final String ATTRTAG_ORDER = "order";

    /*
     * Global Constants
     */
    // Lebesgue Norm Enumerations
    /**
     * l-infinity norm
     */
    public static final int NORM_LINF = 0;

    /**
     * l-1 norm
     */
    public static final int NORM_L1 = 1;

    /**
     * l-2 norm
     */
    public static final int NORM_L2 = 2;

    // Integration accuracy order
    /**
     * Error condition in integration accuracy
     */
    public static final int ACCUR_ERROR = 0;

    /**
     * 1st order accurate integration algorithm
     */
    public static final int ACCUR_ORDER1 = 1;

    /**
     * 2nd order accurate integration algorithm
     */
    public static final int ACCUR_ORDER2 = 2;

    /**
     * Range of available integration accuracies
     */
    public static final int ACCUR_RANGE = 3;

    // IAlgorithm Parameters
    /**
     * string type identifier for algorithm
     */
    public static final String TYPE_ID = EnvTrackerAdapt.class.getName();

    /**
     * current algorithm version
     */
    public static final int VERSION = 2;

    /**
     * probe type recognized by this algorithm
     */
    public static final Class<EnvelopeProbe> CLS_PROBE_TYPE = EnvelopeProbe.class;

    /**
     * The initial step size to start the algorithm.
     */
    private double dlbStepSizeInit;

    /**
     * The current step size.
     */
    private double dblStepSize;

    /**
     * Maximum distance we may travel before requiring another space charge
     * kick. If zero than stepping distance is not bound.
     */
    private double dblMaxStep;

    /**
     * dbleMaxStep for drift field from PMQ
     */
    private double dblMaxStepDriftPmq;

    /**
     * Residual error tolerance parameter. Errors in the the residual between a
     * full step and half step can be no larger than this.
     */
    private double dblErrTol;

    /**
     * Step size adjustment slack tolerance. If adjustments in the step size are
     * less than this percentage, we take special action.
     */
    private double dblSlack;

    /**
     * The type of Lebesque norm used in the residual calculations. Since the
     * residual is a matrix in R7x7 this is a matrix norm.
     */
    private int enmNorm;

    /**
     * The maximum number of iterations through an element before the algorithm
     * aborts propagation. If the iteration count goes beyond the maximum it is
     * assumed that a race condition has occurred. If zero, then there is no
     * maximum iteration count enforced.
     */
    private int intMaxIter;

    /**
     * The order of accuracy used in the integration algorithm
     */
    private int intOrder;

    /**
     * total number of steps taken by algorithm
     */
    private int nDbgSteps;

    /*
     *  Initialization
     */
    /**
     * Creates a new, uninitialized instance of <code>EnvTrackerAdapt</code>
     */
    public EnvTrackerAdapt() {
        super(TYPE_ID, VERSION, CLS_PROBE_TYPE);
        intMaxIter = 50;
        intOrder = EnvTrackerAdapt.ACCUR_ORDER2;
        nDbgSteps = 0;

    }

    /**
     * Copy constructor for EnvTrackerAdapt
     *
     * @param sourceTracker Tracker that is being copied
     */
    public EnvTrackerAdapt(EnvTrackerAdapt sourceTracker) {
        super(sourceTracker);

        this.intMaxIter = sourceTracker.intMaxIter;
        this.intOrder = sourceTracker.intOrder;
        this.nDbgSteps = sourceTracker.nDbgSteps;
        this.dlbStepSizeInit = sourceTracker.dlbStepSizeInit;
        this.dblStepSize = sourceTracker.dblStepSize;
        this.dblMaxStep = sourceTracker.dblMaxStep;
        this.dblMaxStepDriftPmq = sourceTracker.dblMaxStepDriftPmq;
        this.dblErrTol = sourceTracker.dblErrTol;
        this.dblSlack = sourceTracker.dblSlack;
        this.enmNorm = sourceTracker.enmNorm;
    }

    /**
     * Creates a deep copy of EnvTrackerAdapt
     */
    @Override
    public EnvTrackerAdapt copy() {
        return new EnvTrackerAdapt(this);
    }

    /**
     * Initialize the algorithm object for propagation.
     *
     * Internal state of algorithm object is initialized: - Step size is set to
     * initial step size - Start/Stop elements are inspected
     */
    @Override
    public void initialize() {
        super.initialize();
        this.setStepSize(this.getInitStepSize());
    }

    /**
     * Set the initial step size for applying space charge corrections. Note
     * that the step size will be modified as the algorithm progresses according
     * to the adaptation rule.
     *
     * The current step size is reset to this value anytime the
     * <code>initialize()</code> method is called.
     *
     * @param dblStepSize initial step size in <strong>meters</strong>
     *
     * @see EnvTrackerAdapt#setInitStepSize(double)
     * @see EnvTrackerAdapt#initialize()
     */
    public void setInitStepSize(double dblStepSize) {
        dlbStepSizeInit = dblStepSize;
    }

    /**
     * Set the current step size for applying space charge corrections. Note
     * that the step size will be modified as the algorithm progresses according
     * to the adaptation rule.
     *
     * @param dblStepSize initial step size in <strong>meters</strong>
     */
    @Override
    public void setStepSize(final double dblStepSize) {
        this.dblStepSize = dblStepSize;
    }

    /**
     * Set the maximum allowable step size. If this value is set then the step
     * sizing algorithm will never generate steps larger than the provided value
     * regardless of the residual error. If this value is cleared to zero, then
     * the step size is unbound.
     *
     * @param dblMaxStep maximum allowable step size in <strong>meters</strong>
     */
    public void setMaxStepSize(final double dblMaxStep) {
        this.dblMaxStep = dblMaxStep;
    }

    /**
     * Set the maximum allowable step size. If this value is set then the step
     * sizing algorithm will never generate steps larger than the provided value
     * regardless of the residual error. If this value is cleared to zero, then
     * the step size is unbound.
     *
     * @param dblMaxStepDriftPmq maximum allowable step size in
     * <strong>meters</strong>
     */
    public void setMaxStepSizeDriftPmq(final double dblMaxStepDriftPmq) {
        this.dblMaxStepDriftPmq = dblMaxStepDriftPmq;
    }

    /**
     * Sets the maximum allowable number of steps to propagate a probe through
     * an element. If the number of steps increases beyond this number a race
     * condition is assumed and an exception is thrown during the propagation.
     *
     * If the value is zero then no maximum step count is enforced.
     *
     * @param intMaxIter maximum allowable single-element step count
     */
    public void setMaxIterations(int intMaxIter) {
        this.intMaxIter = intMaxIter;
    }

    /**
     * Set the acceptable error in the residual correlation matrix. The residual
     * correlation matrix is determined by going a full step, then two half step
     * and taking the difference in the resulting correlation matrices.
     *
     * The step size is continually adjusted to keep the resulting residual
     * error at or about this given tolerance value. Thus, yield a more accurate
     * solution however they also result in small step sizes.
     *
     * @param dblErr acceptable residual error
     */
    public void setErrorTolerance(final double dblErr) {
        dblErrTol = dblErr;
    }

    /**
     * Set the integration accuracy order for the underlying stepping algorithm.
     * For example, when using a second-order accurate algorithm the residual
     * error is of the order
     * <em>h</em>^2 where <em>h</em> is the step size.
     *
     * @param intOrder integration order
     */
    public void setAccuracyOrder(int intOrder) {
        if (intOrder >= ACCUR_RANGE || intOrder <= ACCUR_ERROR) {
            return;
        }

        this.intOrder = intOrder;
    }

    /**
     * Set the slack size in the adaptive step size determination. That is, if
     * the suggested new step size differs only by this percentage, then no
     * action is taken. Explicitly, if the new step size lies in the interval
     * [h-dblSlack, h+dblSlack], then nothing is done.
     *
     * This feature prevents excessive micro-management of the step size.
     *
     * @param dblSlack size of the slack region in <strong>meters</strong>
     */
    public void setSlackTolerance(final double dblSlack) {
        this.dblSlack = dblSlack;
    }

    /**
     * Set the type of Lebesque norm used in the matrix calculations.
     *
     * @param enmNorm enumeration constant of family
     * <code>EnvTrackerAdapt.NORM_*</code>
     */
    public void setMatrixNorm(final int enmNorm) {
        if (enmNorm < 0 || enmNorm > 2) {
            return;
        }

        this.enmNorm = enmNorm;
    }

    /*
     * Accessing
     */
    /**
     * Return the initial step size for this algorithm. This is the step size
     * when beginning a propagation. Note that the actual step size used
     * afterwards will likely change due to the adaptive nature of the
     * algorithm.
     *
     * @return initial step size in <strong>meters</strong>
     */
    //sako, 21 jul 07
    public double getInitStepSize() {
        return this.dlbStepSizeInit;
    }

    /**
     * Return the current step size, that is, the step size currently used in
     * the propagation.
     *
     * @return the current step size in <strong>meters</strong>
     */
    @Override
    public double getStepSize() {
        return dblStepSize;
    }

    /**
     * Return the maximum allowable number of steps to propagate a probe through
     * an element. If the number of steps increases beyond this number a race
     * condition is assumed and an exception is thrown during the propagation.
     *
     * If the value is zero then no maximum step count is enforced.
     *
     * @return maximum allowable step count while propagating thru a single
     * element
     */
    public int getMaxIterations() {
        return this.intMaxIter;
    }

    /**
     * Return the maximum allowable step size. The step sizing algorithm is
     * bound by this value, or unbounded if zero.
     *
     * @return maximum allowable step size in <strong>meters</strong>
     */
    public double getMaxStepSize() {
        return this.dblMaxStep;
    }

    /**
     * Return the maximum allowable step size. The step sizing algorithm is
     * bound by this value, or unbounded if zero.
     *
     * @return maximum allowable step size in <strong>meters</strong>
     */
    public double getMaxStepSizeDriftPmq() {
        return this.dblMaxStepDriftPmq;
    }

    /**
     * Get the current accuracy order of the space charge stepping algorithm.
     *
     * @return order of the integration algorithm accuracy
     *
     * @see #setAccuracyOrder
     */
    public int getAccuracyOrder() {
        return this.intOrder;
    }

    /**
     * Return the acceptable tolerance in the residual error between a full step
     * and two half steps.
     *
     * @return tolerable residual error
     */
    public double getErrorTolerance() {
        return dblErrTol;
    }

    /**
     * Step size adjustment slack tolerance. If adjustments in the step size are
     * less than this percentage, we do nothing.
     *
     * @return size of the slack region in <strong>meters</strong>
     */
    public double getSlackTolerance() {
        return dblSlack;
    }

    /**
     * Get the type of Lebesque norm used for matrices.
     *
     * @return 0 for l-inf norm, 1 for l-1 norm, 2 for l2 norm
     */
    public int getMatrixNorm() {
        return enmNorm;
    }

    /*
     *  Tracker Abstract Protocol
     */
    /**
     * Propagates the probe through the element using a second-order accurate
     * adaptive step size algorithm for space charge calculations.
     *
     * The new probe state is first computed by taken a full step with the
     * second- order accurate transfer matrix with includes space charge effect.
     * The algorithm then computes the new probe state by taking two half-steps.
     * The residual error (correlation matrix) between the two states is
     * computed. If the norm of the matrix is below the error tolerance (@see
     * #getErrorTolerance) the step may be lengthened. If the residual error is
     * greater than tolerance the step size must be shortened and the new probe
     * state recomputed.
     *
     * @param ifcProbe probe to propagate
     * @param elem element acting on probe
     *
     * @exception ModelException invalid probe type or error in advancing probe
     */
    @Override
    public void doPropagation(IProbe ifcProbe, IElement elem) throws ModelException {
        // Identify probe
        if (!(ifcProbe instanceof EnvelopeProbe)) {
            throw new IllegalArgumentException("Must be of type " + EnvelopeProbe.class.getName());
        }

        EnvelopeProbe probe = (EnvelopeProbe) ifcProbe;

        // If this is a thin element, no space charge calculations are necessary
        if (elem instanceof ThinElement) {
            this.stepThinElement(probe, elem);
            return;
        }

        // Initialize the 2nd order accurate, adaptive step size algorithm
        // current iteration counter
        int iCurCnt = 0;
        // maximum no of iterations
        int iMaxCnt = this.getMaxIterations();

        // location of probe within element
        double s = 0.0;
        // the current step size
        double h = this.getStepSize();
        // length of the element
        double L = elem.getLength();
        EnvelopeProbeState stateRef
                = // initial state of the probe 
                probe.createProbeState();

        //default temporary commented out 
        // this doesnt work for PMQ space-charge=0.. why?
        double charge = probe.bunchCharge();
        // new step size
        double hp;
        // the residual error matrix
        PhaseMatrix matRes;

        do {
            // jdg - if no charge take giant step
            if (charge == 0.) {
                // no space charge - take giant steps
                h = L - s;
            }
            // check if we would step outside the element - if so shorten step 
            if (h + s > L) {
                h = L - s;
            }

            if (getDebugMode()) {
                LOGGER.log(Level.INFO, "charge = {0}", charge);
                LOGGER.log(Level.INFO, "EnvTrackerAdapt, elem, probe.getBeamCharge() = {0} {1}", new Object[]{elem.getId(), probe.bunchCharge()});
                LOGGER.log(Level.INFO, "going to stepProbeState, h, s, L = {0} {1} {2}", new Object[]{h, s, L});
            }

            // Step the probe according to the algorithm, then compute new step size
            matRes = this.stepProbeState(h, probe, elem);
            // I am actuall not sure with space charge=0, effect of fringe field calc step size can be igonored?
            if (charge == 0.) {
                hp = h;
            } else {
                hp = this.compNewStepSize(h, matRes);
            }

            // we stepped too far - roll back and try again
            if (hp < h) {
                this.rollbackProbe(probe, stateRef);

                // our step size meets accuracy criterion - advance probe
            } else {
                stateRef = probe.createProbeState();
                s += h;
            }
            // use the new step size
            h = hp;

            if (this.getDebugMode() == true) {
                if (elem instanceof IdealDrift) {
                    LOGGER.log(Level.INFO, "IdealDrift, hp = " + hp);
                }
                LOGGER.log(Level.INFO, "propagate s=" + probe.getPosition() + " h=" + h + " hp=" + hp + " N=" + nDbgSteps++);
            }

            if (iMaxCnt != 0 && ++iCurCnt >= iMaxCnt) {
                throw new ModelException("EnvTrackerAdapt#doPropagation() - maximum iteration count exceeded.");
            }

            // do while we are still in the element
        } while (s < L);

        // save the last step size as an initial guess for the next time
        this.setStepSize(h);
    }


    /*
     * IContextAware Interface
     */
    /**
     * Load the parameters of this <code>IAlgorithm</code> object from the table
     * data in the given <code>EditContext</code>.
     *
     * Here we load only the parameters specific to the base class. It is
     * expected that Subclasses should override this method to recover the data
     * particular to there own operation.
     *
     * @param strPrimKeyVal primary key value specifying the name of the data
     * record
     * @param ecTableData EditContext containing table data
     *
     * @see xal.tools.data.IContextAware#load(String,
     * xal.tools.data.EditContext)
     */
    @Override
    public void load(String strPrimKeyVal, EditContext ecTableData) throws DataFormatException {
        super.load(strPrimKeyVal, ecTableData);

        // Get the algorithm class name from the EditContext
        DataTable tblAlgorithm = ecTableData.getTable(EnvTrackerAdapt.TBL_LBL_ENVTRACKERADAPT);
        GenericRecord recTracker = tblAlgorithm.record(Tracker.TBL_PRIM_KEY_NAME, strPrimKeyVal);

        if (recTracker == null) {
            // just use the default record
            recTracker = tblAlgorithm.record(Tracker.TBL_PRIM_KEY_NAME, "default");
        }

        final double errorTolerance = recTracker.doubleValueForKey(ATTRTAG_ERRTOL);
        final double initStep = recTracker.doubleValueForKey(ATTRTAG_INITSTEP);
        final double maxStep = recTracker.doubleValueForKey(ATTRTAG_MAXSTEP);
        final double maxStepDriftPmq = recTracker.doubleValueForKey(ATTRTAG_MAXSTEP_DRIFTPMQ);
        final int norm = recTracker.intValueForKey(ATTRTAG_NORM);
        final int order = recTracker.intValueForKey(ATTRTAG_ORDER);
        final double slack = recTracker.doubleValueForKey(ATTRTAG_SLACK);
        final int maxIter = recTracker.intValueForKey(ATTRTAG_MAXITER);

        this.setAccuracyOrder(order);
        this.setMaxIterations(maxIter);

        this.setErrorTolerance(errorTolerance);
        this.setInitStepSize(initStep);
        this.setStepSize(initStep);
        this.setMaxStepSize(maxStep);
        this.setMaxStepSizeDriftPmq(maxStepDriftPmq);
        this.setMatrixNorm(norm);
        this.setSlackTolerance(slack);
    }

    /*
     * IArchive Interface
     */
    /**
     * Load the parameters of the algorithm from a data source exposing the
     * <code>IArchive</code> interface. The superclass <code>load</code> method
     * is called first, then the properties particular to
     * <code>EnvTrackerAdapt</code> are loaded.
     *
     * @see xal.tools.data.IArchive#load(xal.tools.data.DataAdaptor)
     */
    @Override
    public void load(DataAdaptor daptArchive) throws DataFormatException {
        super.load(daptArchive);

        DataAdaptor daptAdapt = daptArchive.childAdaptor(EnvTrackerAdapt.NODETAG_ADAPT);
        if (daptAdapt == null) {
            throw new DataFormatException("EnvTrackerAdapt#load() - missing data node " + EnvTrackerAdapt.NODETAG_ADAPT);
        }

        if (daptAdapt.hasAttribute(ATTRTAG_ORDER)) {
            this.setAccuracyOrder(daptAdapt.intValue(ATTRTAG_ORDER));
        }
        if (daptAdapt.hasAttribute(ATTRTAG_ERRTOL)) {
            this.setErrorTolerance(daptAdapt.doubleValue(ATTRTAG_ERRTOL));
        }
        if (daptAdapt.hasAttribute(ATTRTAG_INITSTEP)) {
            this.setStepSize(daptAdapt.doubleValue(ATTRTAG_INITSTEP));
            this.setInitStepSize(daptAdapt.doubleValue(ATTRTAG_INITSTEP));
        }
        if (daptAdapt.hasAttribute(ATTRTAG_MAXSTEP)) {
            this.setMaxStepSize(daptAdapt.doubleValue(ATTRTAG_MAXSTEP));
        }
        if (daptAdapt.hasAttribute(ATTRTAG_MAXSTEP_DRIFTPMQ)) {
            this.setMaxStepSizeDriftPmq(daptAdapt.doubleValue(ATTRTAG_MAXSTEP_DRIFTPMQ));
        }
        if (daptAdapt.hasAttribute(ATTRTAG_SLACK)) {
            this.setSlackTolerance(daptAdapt.doubleValue(ATTRTAG_SLACK));
        }
        if (daptAdapt.hasAttribute(ATTRTAG_NORM)) {
            this.setMatrixNorm(daptAdapt.intValue(ATTRTAG_NORM));
        }
        if (daptAdapt.hasAttribute(ATTRTAG_MAXITER)) {
            this.setMaxIterations(daptAdapt.intValue(ATTRTAG_MAXITER));
        }
    }

    /**
     * Save the settings particular to this subclass of <code>Tracker</code>.
     * The superclass <code>save</code> method is called first, then the
     * properties particular to <code>EnvTrackerAdapt</code> are saved.
     *
     * @param daptArchive data sink exposing <code>IArchive</code> interface
     *
     * @see xal.tools.data.IArchive#save(xal.tools.data.DataAdaptor)
     */
    @Override
    public void save(DataAdaptor daptArchive) {
        super.save(daptArchive);

        DataAdaptor daptAlg = daptArchive.childAdaptor(Tracker.NODETAG_ALG);
        DataAdaptor daptAdapt = daptAlg.createChild(EnvTrackerAdapt.NODETAG_ADAPT);
        daptAdapt.setValue(ATTRTAG_ORDER, this.getAccuracyOrder());
        daptAdapt.setValue(ATTRTAG_ERRTOL, this.getErrorTolerance());
        daptAdapt.setValue(ATTRTAG_INITSTEP, this.getStepSize());
        daptAdapt.setValue(ATTRTAG_MAXSTEP, this.getMaxStepSize());
        daptAdapt.setValue(ATTRTAG_MAXSTEP_DRIFTPMQ, this.getMaxStepSizeDriftPmq());
        daptAdapt.setValue(ATTRTAG_SLACK, this.getSlackTolerance());
        daptAdapt.setValue(ATTRTAG_NORM, this.getMatrixNorm());
        daptAdapt.setValue(ATTRTAG_MAXITER, this.getMaxIterations());
    }

    /*
     *  Internal Support Functions
     */
    /**
     * new stepThinElement by Sako, taken from EnvelopeTracker Advances the
     * probe state through a subsection of the element with the specified
     * length. Applies a space charge kick at the end of the element subsection
     * for any probe having nonzero beam current.
     *
     * @param ifcElem interface to the beam element
     * @param probe interface to the probe
     *
     * @exception ModelException bad element transfer matrix/corrupt probe state
     */
    protected void stepThinElement(EnvelopeProbe probe, IElement ifcElem) throws ModelException {

        double dblLen = 0;

        // Get initial conditions of probe
        PhaseMatrix res0 = probe.getResponseMatrix();
        CovarianceMatrix chi0 = probe.getCovariance();

        // Get properties of the element
        double L = dblLen;
        //first calculate transfer matrix (mapE, PhiE=Phi)
        PhaseMap mapE = ifcElem.transferMap(probe, L);
        PhaseMatrix PhiE = mapE.getFirstOrder();

        //transfermap
        PhaseMatrix Phi = PhiE;

        PhaseMatrix res1 = Phi.times(res0);
        PhaseMatrix chi1 = chi0.conjugateTrans(Phi);

        if (ifcElem instanceof IdealRfGap) {
            IdealRfGap gap = (IdealRfGap) ifcElem;

            //new 7 Aug 06, Sako
            //correction for sigma matrix
            double sigmaCor[] = this.correctSigmaPhaseSpread(probe, gap);

            double sigmaCorTrans = sigmaCor[0];
            double sigmaCorLong = sigmaCor[1];

            double s11new = chi1.getElem(1, 1) + sigmaCorTrans * chi1.getElem(0, 0);
            chi1.setElem(1, 1, s11new);

            double s33new = chi1.getElem(3, 3) + sigmaCorTrans * chi1.getElem(2, 2);
            chi1.setElem(3, 3, s33new);

            double s55new = chi1.getElem(5, 5) + sigmaCorLong * chi1.getElem(4, 4);
            chi1.setElem(5, 5, s55new);

        }

        // Save the new state variables in the probe
        probe.setResponseMatrix(res1);

        //default
        probe.setCovariance(new CovarianceMatrix(chi1));
        
        this.advanceProbe(probe, ifcElem, 0.0);
    }

    /** 
     * Original code
     * Propagate the probe through a thin element where no space charge effects
     * will occur.
     * 
     * @param probe     probe to propagate
     * @param elem      thin beamline element
     * @throws ModelException   unable to compute transfer matrix for element
     */    
    @SuppressWarnings("unused")
    private void stepThinElementOrg(EnvelopeProbe probe, IElement elem) throws ModelException {
        PhaseMatrix matPhi = this.compElemTransMatrix(0.0, probe, elem);
        PhaseMatrix matResp = matPhi.times(probe.getResponseMatrix());
        PhaseMatrix matChi = probe.getCovariance().conjugateTrans(matPhi);
        Twiss[] twissOld = probe.getCovariance().computeTwiss();

        probe.setResponseMatrix(matResp);

        //sako emittance growth effect for RFGap
        //see RfGap.f of Trace3D        
        //default
        if (elem instanceof IdealRfGap) {
            IdealRfGap gap = (IdealRfGap) elem;

            double sigmaCorTransOld = this.correctTransSigmaPhaseSpread(probe, gap);
            double sigmaCorLongOld = this.correctLongSigmaPhaseSpread(probe, gap);

            //new 7 Aug 06, Sako
            double sigmaCor[] = this.correctSigmaPhaseSpread(probe, gap);

            double sigmaCorTrans = sigmaCor[0];
            double sigmaCorLong = sigmaCor[1];

            if (getDebugMode()) {
                LOGGER.log(Level.INFO, "sigmaCorTrans, sigmaCorTransOld = {0} {1}", new Object[]{sigmaCorTrans, sigmaCorTransOld});
                LOGGER.log(Level.INFO, "sigmaCorLong, sigmaCorLongOld = {0} {1}", new Object[]{sigmaCorLong, sigmaCorLongOld});
            }
            double s11new = matChi.getElem(1, 1) + sigmaCorTrans * matChi.getElem(0, 0);
            matChi.setElem(1, 1, s11new);
            double s33new = matChi.getElem(3, 3) + sigmaCorTrans * matChi.getElem(2, 2);
            matChi.setElem(3, 3, s33new);
            double s55new = matChi.getElem(5, 5) + sigmaCorLong * matChi.getElem(4, 4);
            matChi.setElem(5, 5, s55new);

        }

        probe.setCovariance(new CovarianceMatrix(matChi));

        this.advanceProbe(probe, elem, 0.0);
    }

    /**
     * <p>
     * Advances the <code>probe</code> a distance <code>h</code> through element
     * <code>elem</code>. The probe state is determined using two steps of size
     * <em>h</em>/2. This result is compared to an addition computation where
     * the probe is advance by <em>h</em> using a single step. The residual
     * matrix is returned as an error criterion.
     * </p>
     * <p>
     * The stepping algorithm includes space charge and is second-order
     * accurate. Using "internal extrapolation" with the residual matrix we can
     * produce an answer that is third-order accurate yet the error criterion is
     * only valid to second order.
     * </p>
     *
     * @param h distance to advance probe
     * @param probe probe to advance through element
     * @param elem beamline element acting on probe
     *
     * @return residual error matrix from second-order stepping procedure
     *
     * @throws ModelException unable to compute the element's transfer matrix
     *
     * @see #compTransferMatrix
     * @see #advanceProbe
     */
    private PhaseMatrix stepProbeState(double h, EnvelopeProbe probe, IElement elem)
            throws ModelException {
        // Get the initial state
        PhaseMatrix matRes0 = probe.getResponseMatrix();
        CovarianceMatrix matChi0 = probe.getCovariance();

        // Compute the reference state matChi1
        PhaseMatrix matPhi1 = this.compTransferMatrix(h, probe, elem);
        PhaseMatrix matChi1 = matChi0.conjugateTrans(matPhi1);

        // Compute the double stepped state while advancing probe
        PhaseMatrix matPhi2 = this.compTransferMatrix(h / 2.0, probe, elem);

        PhaseMatrix matRes2 = matPhi2.times(matRes0);
        PhaseMatrix matChi2 = matChi0.conjugateTrans(matPhi2);

        probe.setResponseMatrix(matRes2);
        probe.setCovariance(new CovarianceMatrix(matChi2));

        super.advanceProbe(probe, elem, h / 2.0);

        matPhi2 = this.compTransferMatrix(h / 2.0, probe, elem);

        matRes2 = matPhi2.times(matRes2);
        matChi2 = matChi2.conjugateTrans(matPhi2);

        // Compute the residual matrix and perform internal extrapolation for final state
        PhaseMatrix matRes = matChi2.minus(matChi1);

        probe.setResponseMatrix(matRes2);
        probe.setCovariance(this.compInternExtrap(matRes, matChi2));

        // Update the response matrix without space charge
        PhaseMatrix matRnsp0 = probe.getResponseMatrixNoSpaceCharge();
        PhaseMatrix matPhi_op = elem.transferMap(probe, h).getFirstOrder();
        PhaseMatrix matRnsp1 = matPhi_op.times(matRnsp0);
        probe.setResponseMatrixNoSpaceCharge(matRnsp1);

        super.advanceProbe(probe, elem, h / 2.0);

        return matRes;
    }

    /**
     * Rollback the state of the probe to the given reference state. If the
     * probe update policy is <code>Tracker.UPDATE_ALWAY</code> then we must
     * also eliminate the past two states in the probe's trajectory, which were
     * set by calls to <code>super.advanceProbe
     * </code> in the <code>advanceState</code> method.
     *
     * @param probe probe to be rolled back
     * @param stateRef probe state to reset probe
     *
     * @see Tracker#getProbeUpdatePolicy
     * @see Tracker#advanceProbe
     * @see EnvTrackerAdapt#advanceState
     */
    private void rollbackProbe(EnvelopeProbe probe, EnvelopeProbeState stateRef) {
        probe.applyState(stateRef);

        if (this.getProbeUpdatePolicy() == Tracker.UPDATE_ALWAYS) {
            probe.getTrajectory().popLastState();
            probe.getTrajectory().popLastState();
        }

        if (this.getDebugMode() == true) {
            LOGGER.log(Level.INFO, "ROLLBACK at s={0}", probe.getPosition());
        }
    }

    /**
     * Return the norm of a matrix. The type of norm used to calculated the
     * value is given by <code>getMatrixNorm()</code>.
     *
     * @param mat matrix for which the norm is calculated
     *
     * @return norm of the given matrix
     *
     * @see #getMatrixNorm
     */
    private double compMatrixNorm(PhaseMatrix mat) {

        switch (getMatrixNorm()) {

            case EnvTrackerAdapt.NORM_LINF:
                if (getDebugMode()) {
                    LOGGER.log(Level.INFO, "now NORM_LINF");
                    LOGGER.log(Level.INFO, "trying to print matrix");
                    LOGGER.log(Level.INFO, mat.toStringMatrix());
                }
                return mat.normInf();

            case EnvTrackerAdapt.NORM_L1:
                if (getDebugMode()) {
                    LOGGER.log(Level.INFO, "now NORM_L1");
                    LOGGER.log(Level.INFO, mat.toStringMatrix());
                }
                return mat.norm1();

            case EnvTrackerAdapt.NORM_L2:
                if (getDebugMode()) {
                    LOGGER.log(Level.INFO, "now NORM_L2");
                    LOGGER.log(Level.INFO, mat.toStringMatrix());
                }
                return mat.norm2();

            default:
                if (getDebugMode()) {
                    LOGGER.log(Level.INFO, "now normInf is obtained");
                    LOGGER.log(Level.INFO, mat.toStringMatrix());
                }
                return mat.normInf();
        }
    }

    /**
     * Computes the transfer matrix for the given <code>IElement</code> for a
     * distance <em>h</em> for the given <code>IProbe</code> object.
     *
     * @param h distance for which transfer matrix is valid (in
     * <strong>meters</strong>)
     * @param probe     <code>IProbe</code> object for which transfer matrix is
     * computed
     * @param elem compute transfer matrix for this <code>IElement</code> object
     *
     * @return transfer matrix for <code>elem</code>
     *
     * @throws ModelException transfer matrix computation error - internal to
     * <code>IElement</code>
     */
    private PhaseMatrix compElemTransMatrix(double h, IProbe probe, IElement elem)
            throws ModelException {
        // Get transfer map of the element and take first order component
        PhaseMap mapE = elem.transferMap(probe, h);
        PhaseMatrix matPhiE = mapE.getFirstOrder();

        return matPhiE;
    }

    /*
     * Accuracy Order
     */
    /**
     * Compute the new step size from the error residual and the current step
     * size assuming that the stepping algorithm is first-order accurate. The
     * new step size is determined from the prescribed error tolerance value
     * recovered from <code>#getErrorTolerance()</code> and the norm of the
     * residual (note that the type of norm used is determined by
     * <code>getLebesgueNorm()</code>).
     *
     * @param h current step size
     * @param matRes residual error matrix from the stepping
     *
     * @return new step size
     *
     * @see #getErrorTolerance
     * @see #getLebesgueNorm
     * @see #compMatrixNorm
     */
    private double compNewStepSize(double h, PhaseMatrix matRes) {

        double toler = this.getErrorTolerance();
        double hmax = this.getMaxStepSize();
        double slack = this.getSlackTolerance();
        double error = compMatrixNorm(matRes);

        if (getDebugMode()) {
            if (Math.abs(h) < 1e-5) {
                LOGGER.log(Level.INFO, "compNewStepSize, h = 0");
            }

            LOGGER.log(Level.INFO, "error = {0}", error);
            if (Math.abs(error) < 1e-5) {
                LOGGER.log(Level.INFO, "compNewStepSize, error = 0");
            }
        }

        // Compute the new step size
        // new step size
        double hnew;

        if (this.getAccuracyOrder() == ACCUR_ORDER1) {
            hnew = h * Math.sqrt(toler / error);
        } else {
            hnew = h * Math.pow(toler / error, 1.0 / 3.0);
        }

        if (hmax != 0.0 && hnew > hmax) {
            hnew = hmax;
        } else if (Math.abs((hnew - h) / h) < slack) {
            hnew = h;
        }

        if (this.getDebugMode() == true) {
            LOGGER.log(Level.INFO, "residual error={0}", error);
            LOGGER.log(Level.INFO, "hnew = {0}", hnew);
        }
        return hnew;
    }

    //sako, only for drift with pmq, this is necessary.... 
    /**
     * sako, only for drift with pmq, this is necessary....
     *
     * @param h
     * @param matRes
     * @return
     *
     * @author Christopher K. Allen
     * @since Aug 25, 2011
     */
    private double compNewStepSizeDriftPmq(double h, PhaseMatrix matRes) {

        double toler = this.getErrorTolerance();
        double hmax = this.getMaxStepSizeDriftPmq();
        double slack = this.getSlackTolerance();
        double error = compMatrixNorm(matRes);

        if (this.getDebugMode() == true) {
            if (Math.abs(h) < 1e-5) {
                LOGGER.log(Level.INFO, "compNewStepSizeDriftPmq, h = 0");
            }
            if (Math.abs(error) < 1e-5) {
                LOGGER.log(Level.INFO, "compNewStepSizeDriftPmq, error = 0");
            }
        }
        // Compute the new step size
        // new step size
        double hnew;

        if (this.getAccuracyOrder() == ACCUR_ORDER1) {
            hnew = h * Math.sqrt(toler / error);
        } else {
            hnew = h * Math.pow(toler / error, 1.0 / 3.0);
        }

        if (hmax != 0.0 && hnew > hmax) {
            hnew = hmax;
        } else if (Math.abs((hnew - h) / h) < slack) {
            hnew = h;
        }

        if (this.getDebugMode()) {
            LOGGER.log(Level.INFO, "residual error={0}", error);
        }

        return hnew;
    }

    /**
     * Perform an internal extrapolation to generate an estimate of the probe
     * state (correlation matrix) that is one order higher in accuracy than the
     * algorithm provides. Although the estimate might be higher-order accurate
     * this does not guarantee that it is any closer to the real answer. And we
     * have no way of enforcing any error tolerance.
     *
     * @param matRes the residual error matrix from the two half-step/one whole
     * step process
     * @param matState the new probe state generated by stepping
     *
     * @return an extrapolated value of the probe state
     */
    private CovarianceMatrix compInternExtrap(PhaseMatrix matRes, PhaseMatrix matState) {
        // the extrapolated matrix
        PhaseMatrix matChi;

        if (this.getAccuracyOrder() == ACCUR_ORDER1) {
            matChi = matState.plus(matRes);
        } else {
            matChi = matRes.times(1. / 3.).plus(matState);
        }

        return new CovarianceMatrix(matChi);
    }

    /**
     * Computes the full transfer matrix for a section of length <code>s</code>.
     * The returned transfer matrix is first-order accurate and includes both
     * the effects of the <code>IElement</code> and the effects of space charge.
     *
     * @param h distance for which transfer matrix will propagate probe
     * @param probe the <code>IProbe</code> object for which the transfer matrix
     * is valid
     * @param elem the <code>IElement</code> object
     *
     * @return 7x7 2nd-order accurate transfer matrix in homogeneous phase space
     * coordinates
     *
     * @throws ModelException unable to compute the transfer matrix for the
     * element
     *
     * @see #compElemTransMatrix
     * @see #compScheffTransMatrix
     */
    private PhaseMatrix compTransferMatrix(double h, EnvelopeProbe probe, IElement elem)
            throws ModelException {

        // jdg - bail if no space charge is needed:
        if (probe.bunchCharge() == 0.) {
            return this.compElemTransMatrix(h, probe, elem);
        }

        if (this.getAccuracyOrder() == ACCUR_ORDER1) {
            PhaseMatrix matPhiSc = super.compScheffMatrix(h, probe, elem);

            // We're going to try something different and ensure symplecticity
            // If we are only first-order accurate get the full transfer matrices for the two effects,
            //  multiply them, and return the combined matrix
            PhaseMatrix matPhiE = this.compElemTransMatrix(h, probe, elem);
            PhaseMatrix matPhi = matPhiE.times(matPhiSc);

            return matPhi;
        }

        // Get the transfer matrices for the two individual effects and 
        //  combine them to second-order accuracy (via Campbell-Baker-Hausdorff)        
        // Store the current probe state (for rollback)
        EnvelopeProbeState state0 = probe.cloneCurrentProbeState();

        // Get half-step transfer matrix at current probe location
        PhaseMatrix matPhi0 = this.compElemTransMatrix(h / 2.0, probe, elem);

        // Get the RMS envelopes at probe location
        // covariance matrix at entrance
        CovarianceMatrix covTau0 = probe.getCovariance();

        // Advance probe a half step for position depend transfer maps
        double pos = probe.getPosition() + h / 2.0;
        PhaseMatrix matTau1 = covTau0.conjugateTrans(matPhi0);
        CovarianceMatrix covTau1 = new CovarianceMatrix(matTau1);

        probe.setPosition(pos);
        probe.setCovariance(covTau1);

        // space charge transfer matrix
        PhaseMatrix matPhiSc = this.compScheffMatrix(h, probe, elem);

        // Compute half-step transfer matrix at new probe location        
        PhaseMatrix matPhi1 = this.compElemTransMatrix(h / 2.0, probe, elem);

        // Restore original probe state
        probe.applyState(state0);

        // Compute the full transfer matrix for the distance dblLen
        return matPhi1.times(matPhiSc.times(matPhi0));
    }
}